platform:ios, '10.0'
target 'TestDemo' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'Reachability', '~> 3.2'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'ZBarSDK', '~> 1.3.1'
    pod 'TTTAttributedLabel', '~> 2.0.0'
    pod 'JDStatusBarNotification', '~> 1.5.5'
    pod 'FMDB', '~> 2.6.2'
    pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
    pod 'AMap3DMap-NO-IDFA', '~> 4.6.1'
    pod 'GTSDK', '~> 1.5.3'
    pod 'UMengUShare', '~> 6.3.0'
    pod 'MLeaksFinder', '~> 0.2.1'
end